---
driver_plugin: vagrant

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04-i386_chef-11.4.4.box
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list: ["recipe[wlp]"]
  attributes:
    wlp:
      archive:
        accept_license: "true"
